# Setup
title:               hg.chae
tagline:             'hg.chae theme'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              hg.chae
  url:               ''
  email:             cogudrnr9@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
